version: '3.9'

networks:
  my_network:

volumes:
  postgres_data:

services:
  postgresdb:
    image: postgres:13.4-alpine3.14
    environment:
      POSTGRES_PASSWORD: 'admin1pwd'
      POSTGRES_USER: 'admin'
      POSTGRES_DB: 'service_order'
    networks:
      - my_network
    ports:
      - "5431:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin1 admin1pwd -d service_order" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - .:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data/

  api:
    build: .
    depends_on:
      - postgresdb
    restart:
      always
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py makemigrations && 
            python manage.py migrate && 
            python manage.py runserver"
    networks:
      - my_network
    volumes:
      - ./:/src/

